n1 = input('Entre com um dado')
print('o tipo de variavel é ?:', type(n1))
print('a variavel é um numero ?',n1.isalnum())
print('a variavel é alfabetica ?',n1.isalpha())
print('a variavel é maiucula ?',n1.isupper())
print('a variavel é minuscul ?',n1.islower())
print('a variavel é espaco ?',n1.isspace())
print('a variavel é captalizada ?',n1.istitle())
print('a variavel é alfanumerica ?',n1.isalnum())
